name: Check for git LFS pointers

on:
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      with:
        fetch-depth: 0

    - name: Search for oids in modified lines
      run: |
        $GITHUB_WORKSPACE/commonTools/test/utilities/check-lfs-oids.sh \
        origin/${{ github.event.pull_request.base.ref }} \
        ${{ github.event.pull_request.head.sha }}
